# Generated by Django 4.1.4 on 2022-12-12 22:07

import chat.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=chat.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
